### ISSUE TITLE
Two Test Cases failing for API Unit Test

### ISSUE THREAD

**Issue by PrarabdhJoshi** [PrarabdhJoshi/map-builer#15]
Traceback (most recent call last):
  File "test.py", line 60, in test_get_venue
    self.assertTrue(response.status_code,403)
NameError: global name 'response' is not defined

Traceback (most recent call last):
  File "test.py", line 70, in test_keys_REST
    self.assertTrue('Error' in data)
AssertionError: False is not True

**Comment by PrarabdhJoshi** [comment]
Typo in Error key in the API response object
